package com.github.craftforever.infinitefeatures.blocks;

public enum BlockCallbacks {
    ONDESTROY, ONREMOVEDBYPLAYER, ONEXPLODEDESTROY, ONACTIVATED, ONWALKEDON, ONCLICKED, ONCOLLIDED, ONPLACED, ONFALLENON, ONLANDED, ONHARVESTED, ONEXPLODED, ONPLANTGROW, ONNEIGHBOURCHANGE, ONBLOCKADDED
}